from typing import Protocol, Optional
from uuid import UUID

from app.models import Company, User


class ICompanyRepository(Protocol):
    async def create(self, name: str, industry: Optional[str], country: Optional[str],
                      dataset_namespace: str) -> Company: ...
    async def get_by_id(self, company_id: UUID) -> Optional[Company]: ...
    async def get_by_dataset_namespace(self, namespace: str) -> Optional[Company]: ...


class IUserRepository(Protocol):
    async def create(self, company_id: UUID, email: str, clerk_user_id: str,
                      full_name: Optional[str]) -> User: ...
    async def get_by_id(self, user_id: UUID) -> Optional[User]: ...
    async def get_by_clerk_user_id(self, clerk_user_id: str) -> Optional[User]: ...
    async def get_by_email(self, email: str) -> Optional[User]: ...