"""001_initial_schema

Revision ID: 3b340a75846d
Revises: 
Create Date: 2026-07-03 10:10:26.093875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b340a75846d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('dataset_namespace', sa.String(length=120), nullable=False),
    sa.Column('revenue_estimate_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('onboarding_status', sa.Enum('pending', 'in_progress', 'complete', name='onboarding_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_namespace')
    )
    op.create_table('alerts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('earthquake', 'news_disruption', 'port_closure', 'geopolitical', 'weather', name='event_type_enum'), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('event_source', sa.Enum('usgs', 'gdelt', 'noaa', 'newsapi', name='event_source_enum'), nullable=False),
    sa.Column('event_url', sa.Text(), nullable=True),
    sa.Column('event_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level_enum'), nullable=False),
    sa.Column('affected_products', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('traversal_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('financial_impact_usd_estimate', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('outcome', sa.Enum('disruption_materialised', 'false_positive', name='alert_outcome_enum'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_check_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_jobs',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=60), nullable=False),
    sa.Column('celery_task_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='job_status_enum'), nullable=False),
    sa.Column('progress_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_task_id')
    )
    op.create_table('dataset_namespaces',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('cognee_dataset_name', sa.String(length=120), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('last_cognify_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cognee_dataset_name'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('supplier_forms',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('sent', 'opened', 'submitted', 'expired', name='supplier_form_status_enum'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('risk_analyst', 'procurement_head', 'it_admin', name='user_role_enum'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_history',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('query_type', sa.String(length=60), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('subgraph_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_runs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario_text', sa.Text(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('impact_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_products', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recovery_timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_runs')
    op.drop_table('query_history')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('supplier_forms')
    op.drop_table('dataset_namespaces')
    op.drop_table('background_jobs')
    op.drop_table('alerts')
    op.drop_table('companies')
    # ### end Alembic commands ###
